<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Novolis.Security.Secrets</PackageId>
<IsPackable>true</IsPackable>
  </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\Novolis.Security.WordLists\Novolis.Security.WordLists.csproj" />
      <ProjectReference Include="..\Novolis.Security.Cryptography\Novolis.Security.Cryptography.csproj" />
    </ItemGroup>
</Project>