<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <LibraryReference Include="Novolis.Testing.Logging" />
    <LibraryReference Include="Novolis.Storage.Abstractions" />
    <LibraryReference Include="Novolis.Storage.InMemory" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Novolis.Security.Cryptography\Novolis.Security.Cryptography.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Security.WordLists\Novolis.Security.WordLists.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Security.Secrets\Novolis.Security.Secrets.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Security.PasswordHashing\Novolis.Security.PasswordHashing.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Security.Encryption\Novolis.Security.Encryption.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Security.HaveIBeenPwned\Novolis.Security.HaveIBeenPwned.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Security.SecureText\Novolis.Security.SecureText.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Security.Authentication.Abstractions\Novolis.Security.Authentication.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Security.Authentication\Novolis.Security.Authentication.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Security.Authentication.AspNetCore\Novolis.Security.Authentication.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Security.Authentication.Storage\Novolis.Security.Authentication.Storage.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Security.OAuth.Abstractions\Novolis.Security.OAuth.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Security.OAuth\Novolis.Security.OAuth.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Security.OAuth.AspNetCore\Novolis.Security.OAuth.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Security.OAuth.Storage\Novolis.Security.OAuth.Storage.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Security.Authorization.Abstractions\Novolis.Security.Authorization.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Security.Authorization\Novolis.Security.Authorization.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Security.Authorization.AspNetCore\Novolis.Security.Authorization.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Security.Authorization.Storage\Novolis.Security.Authorization.Storage.csproj" />
  </ItemGroup>
</Project>
